# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Juan Pablo Bertucci
title: M.Sc. University of Illinois at Urbana-Champaign
email: jpb6@illinois.edu
phone: +54-9-11-3428-0390
website: JPchomp.github.io

# Social links
github_username:  JPchomp
instagram_username: hotasinchicago
linkedin_username: jpbertucci


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a MSc. in Sustainable and Resilient Infrastructure Systems program in the Department of Civil and Environmental Engineering at the University of Illinois at Urbana-Champaign. My research interests include <mark>infrastructure engineering</mark>, <mark>statistical learning</mark>, <mark>optimization theory</mark>, <mark>decision theory</mark> and <mark>graphical models</mark>. Primarily, I am interested in developing network infrastructure models that help optimize infrastructure investments. This combines the study of statistics, optimization, risk analysis and physical modelling. Currently I am a member of the [Multi Hazard Approach to Engineering Group](http://mae.cee.illinois.edu/) and transportation consultant at the [Inter American Development Bank](http://iadb.org) 

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# Publications Section
# Publications_title: Publications

# More Section
more_title: Honors & Awards
more_content: |
  - Fulbright Scholarship
  - Argentinian Presidential Fellowship in Science and Technology

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
