# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Juan Pablo Bertucci
title: M.Sc. University of Illinois at Urbana-Champaign
email: jbertucci@fi.uba.ar
phone: +54-9-11-3428-0390

# Social links
github_username:  JPchomp
# instagram_username: hotasinchicago
linkedin_username: jpbertucci
twitter_username: JPbertucci

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I hold a MSc. in Sustainable and Resilient Infrastructure Systems program in the Department of [Civil and Environmental Engineering at the University of Illinois at Urbana-Champaign](https://cee.illinois.edu/). My research interests include <mark>infrastructure</mark>, <mark>statistics</mark>, <mark>optimization</mark> and their practical links to  <mark>transportation</mark>, <mark>public policy</mark> and <mark>decision theory</mark>. I have two research focuses: I collaborate with the [Multi Hazard Approach to Engineering Group](http://mae.cee.illinois.edu/) in developing network models to optimize infrastructure investments subject to catastrophic hazards. I also investigate the social dimensions of transportation in Latin America and the Caribbean along with the [Inter American Development Bank](http://iadb.org), analyzing how transit and shared mobility may help foster an equitable and sustainable mobility landscape for the region.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# Publications Section
# Publications_title: Publications

# More Section
more_title: Honors & Awards
more_content: |
  - Fulbright Scholar
  - Argentinian Presidential Fellowship in Science and Technology

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# Google Analytics
google_analytics: UA-210023023-1
